### ISSUE TITLE
image sequence and opencv version？

### ISSUE THREAD

**Issue by bobibibo123** [lzx1413/mediapipe-lite#7]
Hello, I have a few questions. I noticed that the object detection is tested using an image sequence. Why is it used this way? The previous version of opencv was 3.4.12, but later it was updated to 4.5.5. Why is this?
Looking forward to your reply

**Comment by NrealLzx** [comment]
Hello， 
1. I  test the pipeline with an image sequence because the opencv provided by the offical conan repo is not built with videoio module. Image reader is the easiest way to run this example.  You can read one video if the opencv is ready for this.
2. The conan receipe for opencv 3.4.12 provided by conan has lots of unchangable settings， which is not approprivate for multiplatform testing  such as  android.

**Comment by lzx1413** [comment]
Hello， 
1. I  test the pipeline with an image sequence because the opencv provided by the offical conan repo is not built with videoio module. Image reader is the easiest way to run this example.  You can read one video if the opencv is ready for this.
2. The conan receipe for opencv 3.4.12 provided by conan has lots of unchangable settings， which is not approprivate for multiplatform testing  such as  android.
